import AppKit
import ApplicationServices
import Carbon.HIToolbox

/// Inserts text into the frontmost app and reads its selection.
@MainActor
public enum TextIO {
    public enum Failure: LocalizedError {
        case secureInput, noAccessibility
        public var errorDescription: String? {
            switch self {
            case .secureInput: "Secure Keyboard Entry is on (password field or a terminal setting), so Paluku can't type here. Text copied to clipboard."
            case .noAccessibility: "Paluku needs Accessibility permission to type into other apps."
            }
        }
    }

    public static var hasAccessibility: Bool { AXIsProcessTrusted() }

    public static func requestAccessibility() {
        let key = kAXTrustedCheckOptionPrompt.takeUnretainedValue() as String
        _ = AXIsProcessTrustedWithOptions([key: true] as CFDictionary)
    }

    /// Paste via clipboard + ⌘V, then restore the previous clipboard (all types).
    public static func insert(_ text: String) async throws {
        guard !text.isEmpty else { return }
        let pb = NSPasteboard.general
        if IsSecureEventInputEnabled() {
            pb.clearContents()
            pb.setString(text, forType: .string)
            throw Failure.secureInput
        }
        guard hasAccessibility else {
            pb.clearContents()
            pb.setString(text, forType: .string)
            throw Failure.noAccessibility
        }
        let saved = snapshot(pb)
        pb.clearContents()
        pb.setString(text, forType: .string)
        // Ask clipboard managers not to record this transient paste (nspasteboard.org conventions).
        pb.setData(Data(), forType: NSPasteboard.PasteboardType("org.nspasteboard.TransientType"))
        pb.setData(Data(), forType: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"))
        let marker = pb.changeCount
        postKey(CGKeyCode(kVK_ANSI_V), flags: .maskCommand)
        // Give the target app time to read the pasteboard before restoring it; slow apps (Electron) need more.
        try? await Task.sleep(for: .milliseconds(350))
        if pb.changeCount == marker { restore(pb, saved) }
    }

    public static func pressReturn() { postKey(CGKeyCode(kVK_Return), flags: []) }

    /// Selected text in the focused element: Accessibility first, ⌘C fallback (restores clipboard).
    public static func selectedText() async -> String? {
        if let s = axSelectedText(), !s.isEmpty { return s }
        guard hasAccessibility, !IsSecureEventInputEnabled() else { return nil }
        let pb = NSPasteboard.general
        let saved = snapshot(pb)
        let before = pb.changeCount
        postKey(CGKeyCode(kVK_ANSI_C), flags: .maskCommand)
        for _ in 0..<8 {
            try? await Task.sleep(for: .milliseconds(30))
            if pb.changeCount != before { break }
        }
        let text = pb.changeCount != before ? pb.string(forType: .string) : nil
        if pb.changeCount != before { restore(pb, saved) }
        return text?.isEmpty == false ? text : nil
    }

    public static func axSelectedText() -> String? {
        let system = AXUIElementCreateSystemWide()
        AXUIElementSetMessagingTimeout(system, 1.0)  // global: a hung app must not stall recording start (Electron apps need ~0.5 s)
        var focused: CFTypeRef?
        guard AXUIElementCopyAttributeValue(system, kAXFocusedUIElementAttribute as CFString, &focused) == .success,
            let el = focused, CFGetTypeID(el) == AXUIElementGetTypeID()
        else { return nil }
        var value: CFTypeRef?
        guard AXUIElementCopyAttributeValue(el as! AXUIElement, kAXSelectedTextAttribute as CFString, &value) == .success
        else { return nil }
        return value as? String
    }

    public static func clipboardText() -> String? { NSPasteboard.general.string(forType: .string) }

    // MARK: helpers

    typealias Snapshot = [[NSPasteboard.PasteboardType: Data]]

    static func snapshot(_ pb: NSPasteboard) -> Snapshot {
        (pb.pasteboardItems ?? []).map { item in
            Dictionary(uniqueKeysWithValues: item.types.compactMap { t in item.data(forType: t).map { (t, $0) } })
        }
    }

    static func restore(_ pb: NSPasteboard, _ s: Snapshot) {
        pb.clearContents()
        guard !s.isEmpty else { return }
        pb.writeObjects(
            s.map { dict in
                let item = NSPasteboardItem()
                for (t, d) in dict { item.setData(d, forType: t) }
                return item
            })
    }

    static func postKey(_ key: CGKeyCode, flags: CGEventFlags) {
        let src = CGEventSource(stateID: .combinedSessionState)
        // Neutralise physically-held modifiers (e.g. the trigger key) so ⌘V isn't seen as ⌥⌘V.
        src?.setLocalEventsFilterDuringSuppressionState(
            [.permitLocalMouseEvents, .permitSystemDefinedEvents], state: .eventSuppressionStateSuppressionInterval)
        for down in [true, false] {
            let e = CGEvent(keyboardEventSource: src, virtualKey: key, keyDown: down)
            e?.flags = flags
            e?.post(tap: .cghidEventTap)
        }
    }
}

public struct ActiveApp: Sendable, Equatable {
    public var name: String
    public var bundleID: String?
    public var pid: pid_t

    @MainActor public static var current: ActiveApp? {
        guard let app = NSWorkspace.shared.frontmostApplication else { return nil }
        return ActiveApp(name: app.localizedName ?? "App", bundleID: app.bundleIdentifier, pid: app.processIdentifier)
    }
}
